language: cpp

compiler:
  - gcc
  
before_install:
  # this doesn't work - sudo add-apt-repository -y ppa:timsc/opencv-3.3
 # - sudo apt-get update

install:

# OpenCV install code (modified from orignal source: https://github.com/jayrambhia/Install-OpenCV)
#just test github deploy
  
before_script:
  - cd build
 # - cmake ..

script: 
#  - make GL_warp2mp4.bin
   
  # modified from https://github.com/lupoDharkael/smilla-enlarger/pull/2/files

  

after_success:
deploy:
  provider: releases
  api_key: "eb02d01056d0fc1878301a1076c495e1aa481a4c"
  file_glob: true
  file: *.map
  skip_cleanup: true
  draft: true
